using System; // Imports the fundamental classes and base data types used in C#
using System.Windows.Forms; // Imports classes for creating Windows-based applications with a graphical user interface (GUI)

namespace Coursework_GUI // Defines a namespace to organize and group related code
{
    public partial class Main : Form // Defines the 'Main' class, which is a 'partial' class inheriting from 'Form' (making it a window/form)
    {
        // Constructor for Main form
        public Main() // The constructor method, which is called when an instance of the Main form is created
        {
            InitializeComponent();  // Method generated by the Visual Studio designer to set up the form's controls and layout
        }

        // This event is triggered when the form loads
        private void Form1_Load(object sender, EventArgs e) // Event handler method called when the Main form finishes loading
        {
            // Seed sample data for coursework (this only runs once when the form is first loaded)
            if (DataStore.Users.Count == 0) // Checks if the static list of users in the DataStore class is empty (no users have been added yet)
            {
                // Add a sample teacher to the DataStore
                DataStore.AddPerson(new Teacher // Calls a method to add a new person object to the data store
                {
                    Name = "John Smith", // Sets the Name property of the new Teacher object
                    Telephone = "0123456789", // Sets the Telephone property
                    Email = "john@example.com", // Sets the Email property
                    Salary = 30000, // Sets the specific Salary property for the Teacher
                    Subject1 = "Maths", // Sets the Subject1 property
                    Subject2 = "Physics" // Sets the Subject2 property
                });

                // Add a sample student to the DataStore
                DataStore.AddPerson(new Student // Calls the method to add a new person object
                {
                    Name = "Alice", // Sets the Name property of the new Student object
                    Telephone = "0987654321", // Sets the Telephone property
                    Email = "alice@example.com", // Sets the Email property
                    Subject1 = "Programming", // Sets the Subject1 property for the Student
                    Subject2 = "Database", // Sets the Subject2 property
                    Subject3 = "Networks" // Sets the Subject3 property
                });

                // Add a sample admin staff to the DataStore
                DataStore.AddPerson(new AdminStaff // Calls the method to add a new person object
                {
                    Name = "Mary Admin", // Sets the Name property of the new AdminStaff object
                    Telephone = "0111222333", // Sets the Telephone property
                    Email = "admin@example.com", // Sets the Email property
                    Salary = 25000m, // Sets the Salary property, using 'm' suffix for decimal literal
                    IsFullTime = true, // Sets the specific IsFullTime property for the AdminStaff
                    WorkingHours = 40 // Sets the specific WorkingHours property
                });
            }
        }

        // Event triggered when the "Add User" button is clicked
        private void btnAddUser_Click(object sender, EventArgs e) // Event handler method for the 'Add User' button click
        {
            // Open the UserForm to add a new user
            using (var f = new UserForm()) // Creates a new instance of UserForm and ensures it's properly disposed when finished ('using' statement)
            {
                // The UserForm is responsible for:
                // - Asking the user to select a role (Teacher/Student/AdminStaff)
                // - Entering details like Name, Telephone, Email, Salary/Subjects, etc.
                // - Calling DataStore.AddPerson(newUser) when Save is clicked
                var result = f.ShowDialog(); // Displays the UserForm modally (pausing execution of Main form until UserForm is closed) and captures the result (e.g., OK, Cancel)

                if (result == DialogResult.OK) // Checks if the UserForm was closed by clicking the 'Save' or 'OK' button
                {
                    // Show a success message after adding the user successfully
                    MessageBox.Show("User added successfully.", // Displays a standard message box to the user
                        "Information", // Sets the title of the message box
                        MessageBoxButtons.OK, // Specifies that the message box should only have an 'OK' button
                        MessageBoxIcon.Information); // Specifies the information icon to be displayed
                }
            }
        }

        // Event triggered when the "View All Users" button is clicked
        private void btnViewAllUsers_Click(object sender, EventArgs e) // Event handler method for the 'View All Users' button click
        {
            // Open the UserListForm to display all users in a list
            using (var f = new UserListForm()) // Creates a new instance of UserListForm, ensuring disposal with 'using' statement
            {
                f.ShowDialog(); // Displays the UserListForm modally
            }
        }

        // Empty event handler for pictureBox2 click
        private void pictureBox2_Click(object sender, EventArgs e) { }

        // Empty event handler for the Paint event of panelMain (if custom painting is needed)
        private void panelMain_Paint(object sender, PaintEventArgs e) { }
    }
}